<?php
/*
FileManager version 1.0.0
Daniel Riera

EL AUTOR OFRECE ESTE SOFTWARE "TAL CUAL" Y RECHAZA TODAS LAS GARANTÍAS EXPRESAS O
TÁCITAS, INCLUIDAS, A TÍTULO ENUNCIATIVO AUNQUE NO LIMITATIVO, LAS GARANTÍAS 
IMPLÍCITAS DE COMERCIABILIDAD E IDONEIDAD PARA UN FIN EN PARTICULAR. EN NINGÚN
CASO EL AUTOR SERÁ RESPONSABLE POR NINGÚN DAÑO DIRECTO, INDIRECTO, INCIDENTAL, 
ESPECIAL, EJEMPLAR NI CONSECUENTE (INCLUIDA, A TÍTULO ENUNCIATIVO AUNQUE NO 
LIMITATIVO, LA ADQUISICIÓN DE BIENES Y SERVICIOS SUSTITUTOS, LA PÉRDIDA DE USO,
DATOS O GANANCIAS, O LA INTERRUPCIÓN DE LAS OPERACIONES COMERCIALES), SIN 
IMPORTAR LA CAUSA Y EN CUALQUIER BASE DE RESPONSABILIDAD, YA SEA CONTRACTUAL, 
RESPONSABILIDAD NO CULPOSA O DAÑO EXTRACONTRACTUAL (POR NEGLIGENCIA O NO) 
QUE SURJA DE CUALQUIER MODO A PARTIR DEL USO DE ESTE SOFTWARE, INCLUSO SI 
SE NOTIFICÓ DE LA POSIBILIDAD DE DICHO DAÑO.

*/

//Configuración

$directorio = "";
$seguridad = "0000";
?>